on:
  push:
    branches: [release-ci]

jobs:
  master_test:
    runs-on: macos-latest

    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: install pods  
        run: |
          pod install

      - name: build app
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          xcodebuild -workspace NiceDishy.xcworkspace -scheme "$SCHEME" install DSTROOT=build/root | xcpretty

      - name: package app
        run: |
          hdiutil create \
                  -fs HFS+ \
                  -srcfolder "build/root/Applications/NiceDishy.app" \
                  -volname "NiceDishy" "build/NiceDishy.dmg"
