on:
  push:
    branches: [ci]
  pull_request:
    branches: [main]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: swift test
        env:
          DEVELOPER_DIR: /Applications/Xcode_13.1.app/Contents/Developer
